minimumReleaseAge: 4320 # 3日

onlyBuiltDependencies:
  - esbuild
  - sharp
  - spawn-sync

blockExoticSubdeps: true

strictDepBuilds: true

trustPolicy: no-downgrade
minimumReleaseAgeExclude:
  # Renovate security update: vite@8.0.16
  - vite@8.0.16
